
const routes = {
    introduce: '/',
    addminAddInventory: "/addmin/addinventory",
    addminInventorys: "/addmin/inventorys",
    unauthorization: "/unauthorization",
    account: "/account",
    addmin: "/account/addmin",
    employment: "/account/employment",
    user: "/account/user",
    login: "/account/login",
    register: "/account/register",
    recoverPwd: "/account/recover",
    detailProduct: "/products/:title",
    cancel: "/payment/cancel",
    success: "/payment/success/:customerID",
    checkout: "/checkout",
    cart: "/cart",
    shopAll: "/collections/shopAll",
    scrapbooks: '/collections/scrapbooks',
    newArrivals: '/collections/newArrivals',
    outerwear: "/collections/outerwear",
    sweatshirts: "/collections/sweatshirts",
    tops: "/collections/tops",
    tees: "/collections/tees",
    pants: "/collections/pants",
    accessories: "/collections/accessories",
}

export default routes